version: '3.8'

services:
  nextjs-typescript:
    ports:
      - 3000:3000
    build:
      context: ./nextjs
    volumes:
      - ./nextjs:/app

  strapi:
    build: ./strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - AUTHENTICATION_DATABASE=strapi
    volumes:
      - ./strapi:/opt/app/
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
